-- Seed KLiC courses from MKCL website
INSERT INTO public.courses (name, subtitle, description, duration, lectures, certificate, category, popular, image_url, display_order) VALUES
('MS-CIT', 'Maharashtra State Certificate in IT', 'सर्वात लोकप्रिय संगणक अभ्यासक्रम. MS Office, Internet, Email, Windows operating system यांचे संपूर्ण प्रशिक्षण.', '3 महिने', 48, 'MKCL Certified', 'mkcl', true, 'https://klic.mkcl.org/user/pages/images/courses/KLiC-MS-CIT.jpg', 1),
('KLiC Advanced Excel', 'Data Analysis & Business Intelligence', 'डेटा संकलन, विश्लेषण आणि व्यवसाय अंदाज. Pivot Tables, Charts, Macros, VBA यांचे प्रशिक्षण.', '120 तास', 40, 'MKCL Certified', 'mkcl', true, 'https://klic.mkcl.org/user/pages/images/courses/KLiC-Advanced-Excel-2023.jpg', 2),
('KLiC AI', 'Artificial Intelligence Fundamentals', '100+ AI tools, Cyber Security, आणि practical AI literacy. ChatGPT, Gemini, AI Image Generation शिका.', '30 तास', 20, 'MKCL Certified', 'mkcl', true, 'https://klic.mkcl.org/user/pages/images/courses/KLiC-AI-ML-2024.jpg', 3),
('KLiC AI-ML Basics', 'Machine Learning Fundamentals', 'Intelligence concepts, ethical considerations, आणि model functioning. Python, TensorFlow basics.', '60 तास', 30, 'MKCL Certified', 'mkcl', false, 'https://klic.mkcl.org/user/pages/images/courses/KLiC-AI-ML-2024.jpg', 4),
('KLiC AutoCAD', '2D & 3D Design', 'Architecture आणि engineering साठी floor plans, design editing. Professional drafting skills.', '120 तास', 45, 'MKCL Certified', 'mkcl', false, 'https://klic.mkcl.org/user/pages/images/courses/KLiC-AutoCAD-2023.jpg', 5),
('KLiC BFSI', 'Banking & Financial Services', 'Banking systems, mobile banking, internet banking. Financial sector साठी practical training.', '120 तास', 50, 'MKCL Certified', 'mkcl', false, 'https://klic.mkcl.org/user/pages/images/courses/KLiC-BFSI-2023.jpg', 6),
('KLiC C & C++ Programming', 'Programming Fundamentals', 'Software development साठी foundational programming. Logic building, algorithms, data structures.', '120 तास', 50, 'MKCL Certified', 'mkcl', false, 'https://klic.mkcl.org/user/pages/images/courses/KLiC-C-CPP-2023.jpg', 7),
('KLiC Tally Prime', 'Accounting Software', 'GST Accounting, Inventory Management, Payroll. व्यवसायिक हिशोब व्यवस्थापन.', '90 तास', 40, 'MKCL Certified', 'mkcl', true, 'https://klic.mkcl.org/user/pages/images/courses/KLiC-Tally-2023.jpg', 8),
('KLiC DTP', 'Desktop Publishing', 'Photoshop, CorelDraw, PageMaker. Graphic design आणि print media साठी.', '90 तास', 35, 'MKCL Certified', 'mkcl', false, 'https://klic.mkcl.org/user/pages/images/courses/KLiC-DTP-2023.jpg', 9),
('KLiC Web Development', 'Website Design & Development', 'HTML, CSS, JavaScript, WordPress. Modern websites तयार करायला शिका.', '120 तास', 50, 'MKCL Certified', 'mkcl', false, 'https://klic.mkcl.org/user/pages/images/courses/KLiC-WebDev-2023.jpg', 10),
('English Typing', 'Professional Typing Speed', 'Touch typing, speed building, accuracy improvement. 40+ WPM साठी.', '2 महिने', 30, 'Institute Certificate', 'typing', true, 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600', 11),
('Marathi Typing', 'मराठी टायपिंग', 'ISM, Shree Lipi, Unicode typing. Government exams साठी आवश्यक.', '2 महिने', 30, 'Institute Certificate', 'typing', true, 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600', 12),
('CCC', 'Course on Computer Concepts', 'NIELIT certified course. सरकारी नोकरी साठी आवश्यक computer certificate.', '3 महिने', 40, 'NIELIT Certified', 'government', true, 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600', 13),
('O Level', 'NIELIT O Level', 'Foundation level IT course by NIELIT. Programming, networking basics.', '1 वर्ष', 100, 'NIELIT Certified', 'government', false, 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600', 14),
('Basic Computer Course', 'Computer Fundamentals', 'Windows, MS Office, Internet basics. नवशिक्यांसाठी योग्य.', '2 महिने', 25, 'Institute Certificate', 'skills', true, 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600', 15)
ON CONFLICT DO NOTHING;